//! Generating and checking the `THIRD_PARTY.md` notices file.

use crate::tree;
use crate::util::{self, Error, Result};
use std::path::{Path, PathBuf};

/// `{p}` = `name vX.Y.Z`, `{l}` = the licence, `{r}` = the repository URL.
const TREE_FORMAT: &str = "{p}|{l}|{r}";

const PREAMBLE: &str = "\
# Third-party notices

<!-- @generated by cargo xtask licenses - do not hand-edit the crate table.
     Regenerate with `cargo xtask licenses`; the assets section is hand-written,
     between the assets:begin/end markers only. -->

The third-party crates that may end up in a binary this repository ships, and their
licences. The list is the union of `cargo tree --workspace -e normal --all-features`
run for two targets (`x86_64-unknown-linux-gnu`, `aarch64-unknown-linux-gnu`), with
this workspace's own crates excluded. Build-only and dev-only dependencies are not
here, because they are not in what ships (`-e normal`).

The licence policy is enforced by `deny.toml` and `deps.allow`; how a dependency is
approved is in `CONTRIBUTING.md`.
";

const ASSETS_INTRO: &str = "\
## Assets

Assets are not crates, so they are outside `cargo-deny`'s reach.
Anything that enters the repository as an asset - icon SVGs, fonts - is listed here,
with the original licence file kept at `assets/<group>/LICENSE-*`. Adding an asset
follows the same approval procedure as a dependency, and an asset PR has to update
this section.

Only what is **between the two markers below** is hand-written.
`cargo xtask licenses` preserves that region verbatim, and `--check` does not compare
it.

";

/// The markers for the start and end of the hand-managed assets region.
const ASSETS_BEGIN: &str = "<!-- assets:begin -->";
const ASSETS_END: &str = "<!-- assets:end -->";

/// The default table used while there are no assets yet.
const ASSETS_DEFAULT: &str = "\
| Asset | Source | Licence | File |
|---|---|---|---|
| (none) | | | |";

/// Take the hand-managed assets region out of an existing file. `None` where the markers are missing.
fn assets_block(text: &str) -> Option<&str> {
    let (_, rest) = text.split_once(ASSETS_BEGIN)?;
    let (inner, _) = rest.split_once(ASSETS_END)?;
    Some(inner.trim_matches('\n'))
}

/// `THIRD_PARTY.md`'s path.
pub(crate) fn path(root: &Path) -> PathBuf {
    root.join("THIRD_PARTY.md")
}

/// The copy inside `crates/fairing`, which the shell's licence screen embeds
/// (`settings.licences`). A published crate can only `include_str!` what is inside its own
/// folder, so the notices live at the root for people and inside the crate for the build; the
/// two are the same bytes, and stage 10 fails where they are not.
pub(crate) fn crate_copy(root: &Path) -> PathBuf {
    root.join("crates").join("fairing").join("THIRD_PARTY.md")
}

/// Build the notices file's body from the current tree. For the same tree and the same assets region it is always the same content.
pub(crate) fn render(root: &Path, assets: &str) -> Result<String> {
    let packages = tree::collect_union(root, TREE_FORMAT)?;
    let mut out = String::from(PREAMBLE);
    out.push_str("\n## Crates (");
    out.push_str(&packages.len().to_string());
    out.push_str(")\n\n");
    out.push_str("| Crate | Version | Licence | Repository |\n|---|---|---|---|\n");
    for pkg in &packages {
        let license = if pkg.license.is_empty() {
            "(not stated — to be confirmed before approval)".to_owned()
        } else {
            escape(&pkg.license)
        };
        let repository = repository_cell(&pkg.repository);
        out.push_str("| ");
        out.push_str(&escape(&pkg.name));
        out.push_str(" | ");
        out.push_str(&escape(&pkg.version));
        out.push_str(" | ");
        out.push_str(&license);
        out.push_str(" | ");
        out.push_str(&repository);
        out.push_str(" |\n");
    }
    out.push('\n');
    out.push_str(ASSETS_INTRO);
    out.push_str(ASSETS_BEGIN);
    out.push('\n');
    out.push_str(assets.trim_matches('\n'));
    out.push('\n');
    out.push_str(ASSETS_END);
    out.push('\n');
    Ok(out)
}

/// Escape, minimally, only the characters whose meaning would break inside the table.
fn escape(text: &str) -> String {
    text.replace('|', "\\|")
}

/// The repository column. It is a string the crate provided, so it is used as it stands only where it
/// is an ordinary URL; anything else is wrapped in code notation so it is not read as markdown (a link or HTML).
fn repository_cell(url: &str) -> String {
    if url.is_empty() {
        return String::new();
    }
    if is_plain_url(url) {
        return escape(url);
    }
    format!("`{}`", escape(url).replace('`', "'"))
}

fn is_plain_url(url: &str) -> bool {
    let scheme_ok = url.starts_with("https://") || url.starts_with("http://");
    scheme_ok
        && url.len() <= 200
        && !url.chars().any(|c| {
            c.is_whitespace() || matches!(c, '<' | '>' | '(' | ')' | '[' | ']' | '`' | '\\')
        })
}

/// Write the file.
pub(crate) fn write(root: &Path) -> Result<()> {
    let file = path(root);
    let previous = if file.exists() {
        util::read_file(&file)?
    } else {
        String::new()
    };
    let assets = assets_block(&previous).unwrap_or(ASSETS_DEFAULT).to_owned();
    let contents = render(root, &assets)?;
    util::write_file(&file, &contents)?;
    let copy = crate_copy(root);
    util::write_file(&copy, &contents)?;
    println!("refreshed {} and {}.", file.display(), copy.display());
    Ok(())
}

/// Stage 10: check that the file matches the current tree. `true` on a pass.
pub(crate) fn check(root: &Path) -> Result<bool> {
    let file = path(root);
    let actual = if file.exists() {
        util::read_file(&file)?
    } else {
        return Err(Error::new(format!(
            "{} is missing. Build it with `cargo xtask licenses`",
            file.display()
        )));
    };
    // The assets region is managed by hand and so is not compared.
    let Some(assets) = assets_block(&actual) else {
        println!(
            "{} has no assets:begin/assets:end markers. Refresh it with `cargo xtask licenses`.",
            file.display()
        );
        return Ok(false);
    };
    let expected = render(root, assets)?;
    if actual != expected {
        println!(
            "{} differs from the current dependency tree. Refresh it with `cargo xtask licenses`.",
            file.display()
        );
        print_diff(&actual, &expected);
        return Ok(false);
    }
    let copy = crate_copy(root);
    let copied = if copy.exists() {
        util::read_file(&copy)?
    } else {
        String::new()
    };
    if copied != actual {
        println!(
            "{} is not the same as {}. Refresh both with `cargo xtask licenses`.",
            copy.display(),
            file.display()
        );
        return Ok(false);
    }
    println!("{} and its crate copy are up to date.", file.display());
    Ok(true)
}

/// Cut the common head and tail off line by line and show only the differing region.
fn print_diff(actual: &str, expected: &str) {
    let old: Vec<&str> = actual.lines().collect();
    let new: Vec<&str> = expected.lines().collect();
    let head = old
        .iter()
        .zip(new.iter())
        .take_while(|(a, b)| a == b)
        .count();
    let tail = old
        .iter()
        .rev()
        .zip(new.iter().rev())
        .take_while(|(a, b)| a == b)
        .count()
        .min(old.len().saturating_sub(head))
        .min(new.len().saturating_sub(head));
    let shown = 12_usize;
    for line in old
        .get(head..old.len() - tail)
        .unwrap_or(&[])
        .iter()
        .take(shown)
    {
        println!("  - {line}");
    }
    for line in new
        .get(head..new.len() - tail)
        .unwrap_or(&[])
        .iter()
        .take(shown)
    {
        println!("  + {line}");
    }
}

#[cfg(test)]
mod tests {
    use super::{assets_block, escape, repository_cell, ASSETS_BEGIN, ASSETS_END};

    #[test]
    fn escapes_table_separators() {
        assert_eq!(escape("MIT|Apache-2.0"), "MIT\\|Apache-2.0");
        assert_eq!(escape("MIT OR Apache-2.0"), "MIT OR Apache-2.0");
    }

    #[test]
    fn keeps_the_hand_written_assets_block() {
        let text = format!(
            "before\n{ASSETS_BEGIN}\n| Icons | lucide | ISC | assets/icons |\n{ASSETS_END}\nafter\n"
        );
        assert_eq!(
            assets_block(&text),
            Some("| Icons | lucide | ISC | assets/icons |")
        );
        assert_eq!(assets_block("no markers"), None);
    }

    #[test]
    fn only_plain_urls_go_in_bare() {
        assert_eq!(
            repository_cell("https://github.com/rust-lang/log"),
            "https://github.com/rust-lang/log"
        );
        assert_eq!(repository_cell(""), "");
        // A value that would be read as a markdown link or HTML is caged in code notation.
        assert_eq!(
            repository_cell("x](javascript:alert(1))"),
            "`x](javascript:alert(1))`"
        );
        assert_eq!(repository_cell("<img src=x>"), "`<img src=x>`");
    }
}
